### ISSUE TITLE
Тестовая задача. Весна 2019

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/LangToGroup#14]
Реализовать на Haskell интерпретатор детерминированных конечных автоматов. На вход принимается автомат и набор цепочек (формат входа на ваше усмотрение), на выходе генерируется файл в формате TeX, содержащий описание автомата и трассу обработки им каждой цепочки. TeX-файл должен быть готов к компиляции с помощью pdflatex без дополнительных действий. 

Ответ: ссылка на репозиторий с решением в комментариях к этому issue.

Вопросы можно здавать здесь же.

**Comment by wafemand** [comment]
https://github.com/wafemand/DFA_Interpreter/tree/master
